#################################################
# This file is a sample of some things you 
# can do with this leader key setup. It's active
# right now! Set leader_key below and try it! The 
# lua prioritizes home.toml, then work.toml,
# then falls back to this sample.toml. If you
# want different profile names, you can add it
# to the list in ~/.hammerspoon/init.lua. 
#################################################

# settings
leader_key = "space"        # required, the leader key that starts the sequence
leader_key_mods = "cmd"      # optional, default "", not recommended - a dedicated leader key is better
                             # supports cmd ctrl alt shift
auto_reload = true        # optional, default true, reload when any file in this directory is saved
toast_on_reload = false    # optional, default false, show a toast when the config is reloaded
show_ui = true            # optional, default true, show the ui with your key maps
key_maps_per_line = 4     # optional, default 5, number of key maps per line in the ui

# JIRA Search
# JIRA Me
# Search Files
# Eject All Disks

q = ["esc", "Quit"]

e = ["raycast://extensions/raycast/emoji-symbols/search-emoji-symbols", "Emoji"]
m = ["raycast://extensions/raycast/calendar/my-schedule", "Meetings"]

[h]
label = "Home"
m = ["hs:hs.shortcuts.run('MeetingAction')", "Meeting Lights"]
s = ["hs:hs.shortcuts.run('ScreenAction')", "Meeting Lights"]
n = ["hs:hs.shortcuts.run('BackgroundNoise')", "Noise"]

[g]
label = "Go to App"
a = ["Affinity Photo 2", "Affinity Photo"]
c = ["Google Chrome", "Chrome"]
e = ["Microsoft Excel", "Excel"]
f = ["cmd: open ~/Documents", "Finder"]
g = ["Ghostty", "Ghostty"]
i = ["iTerm", "iTerm"]
k = ["KeePassXC", "KeePass"]
m = ["Obsidian", "Obsidian"]
n = ["Notes", "Notes"]
o = ["Microsoft Outlook", "Outlook"]
p = ["Preview", "Preview"]
r = ["raycast://raycast", "Raycast"]
s = ["Safari", "Safari"]
t = ["Microsoft Teams", "Teams"]
w = ["Microsoft Word", "Word"]
x = ["OmniFocus", "OmniFocus"]
z = ["ZED", "ZED"]

["/"]
label = "Tools"
c = ["Calculator", "Calculator"]
p = ["Digital Color Meter", "Color Picker"]
m = ["shortcut:cmd shift m", "Mute/Unmute"]
s = ["shortcut:cmd shift 4", "Screenshot"]
g = ["input:cmd:open 'https://google.com/search?q={input}'", "Google Search"]
l = ["input:cmd:open 'https://maps.google.com/maps?q={input}'", "Maps Search"]
r = [ "reload", "Reload config" ]

[n]
label = "New"
t = ["menu:Safari|Ablage>Neuer Tab","New Tab"]

[l]
label = "Links"
g = "https://google.de"

[s]
label = "macOS"
p = ["cmd: open x-apple.systempreferences:com.apple.preference.security?General", "Privacy"]
c = ["cmd: open x-apple.systempreferences:com.apple.preference.security?Privacy_Camera", "Privacy Camera"]
m = ["cmd: open x-apple.systempreferences:com.apple.preference.security?Privacy_Microphone", "Security Microphone"] 
b = ["cmd: open x-apple.systempreferences:com.apple.BluetoothSettings", "Bluetooth"]
d = ["cmd: open x-apple.systempreferences:com.apple.Displays-Settings.extension", "Displays"]
n = ["cmd: open x-apple.systempreferences:com.apple.Network-Settings.extension", "Network"]
k = ["cmd: open x-apple.systempreferences:com.apple.preference.keyboard", "Keyboard"]
s = ["cmd: open '/System/Applications/System Settings.app'", "Settings"]
[s.a]
label = "Audio"
s = ["cmd: open x-apple.systempreferences:com.apple.preference.sound", "Settings"]
i = ["hs:hs.audiodevice.findOutputByName('MacBook Pro-Lautsprecher'):setDefaultOutputDevice()", "Internal"]
m = ["hs:hs.audiodevice.defaultOutputDevice():setMuted(not hs.audiodevice.defaultOutputDevice():muted())", "Mute toggle"]

[r]
label = "Raycast"
r = ["raycast://raycast", "Raycast"]
f = ["raycast://extensions/raycast/raycast-focus/toggle-focus-session", "Toggle Focus Session"]
c = ["raycast://extensions/raycast/raycast/confetti", "Confetti"]
l = ["raycast://extensions/raycast/system/lock-screen", "Lock"]
s = ["raycast://extensions/raycast/system/sleep", "Sleep"]
d = ["raycast://extensions/raycast/system/sleep-displays", "Sleep display"]
h = ["raycast://extensions/raycast/system/hide-all-apps-except-frontmost", "Hide others"]
u = ["raycast://extensions/raycast/system/unhide-all-hidden-apps", "Unhide all"]
b = ["raycast://extensions/raycast/clipboard-history/clipboard-history", "Clipboard History"]

[t]
label = "Text"
l = ["text:Liebe Grüße\n", "LG"]
[t.m]
label = "Mail"
i= ["text:example@example.com", "Info"]

[w]
label = "Window"
n=["hs:switchWindow()","Next window"]
m = ["cmd:open -a 'Mission Control'", "Mission Control"]

[o]
label = "Open"
d = ["cmd:open ~/Documents", "Documents"]
w = ["cmd:open ~/Downloads", "Downloads"]

[w.s]
label = "Size"
h = ["window:left-half","Left half"]
l = ["window:right-half","Right half"]
c = ["window:center-half","Center half"]
m = ["window:maximized","Maximized"]
f = ["window:fullscreen","Fullscreen"]
k = ["window:top-half","Top half"]
j = ["window:bottom-half","Bottom half"]
u = ["window:left-third","Left third"]
i = ["window:center-third","Center third"]
o = ["window:right-third","Right third"]

[w.d]
label = "Display"
h=["hs:moveToScreenWest()","West"]
l=["hs:moveToScreenEast()","East"]
j=["hs:moveToScreenSouth()","South"]
k=["hs:moveToScreenNorth()","North"]

[w.f]
label = "Focus"
h=["hs:moveToWindowWest()","West"]
l=["hs:moveToWindowEast()","East"]
j=["hs:moveToWindowSouth()","South"]
k=["hs:moveToWindowNorth()","North"]
